# docker-compose.yml
version: '3.8'
services:
  db:
    image: postgres:14
    container_name: telemedicine_db
    restart: always
    ports:
      - "5499:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: telemedicine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: